### ISSUE TITLE
Create Instructional Design homepage and skeleton

### ISSUE THREAD

**Issue by jmakowski1123** [openedx/docs.openedx.org#212] opened 2022-11-15 23:22 UTC
Next steps to integrate #173 and Shannon's Instructional design documents.

- [ ] Create a sub-page for instructional designers underneath the Educator persona
- [ ] Create skeleton outline for the references and concepts docs https://docs.google.com/spreadsheets/d/1AVg4jjSUA6yBMHSlYj9kn8Vv9KeCf3GcimnD4M4K4XI/edit#gid=0
- [ ] Review with Shannon and John (meeting set early Dec)

**Comment by feanil** [comment] 2022-12-09 15:44
Closing as a duplicate of https://github.com/openedx/docs.openedx.org/issues/219

**Closed by feanil** 2022-12-09 15:44 UTC
Labels: duplicate :dancing_men:
